baseURL = "https://lokal.ninja/nordrhein-westfalen"
languageCode = "de-DE"
title = "Lokal Ninja - Nordrhein-Westfalen"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML"]

[params]
  org = "lokal-ninja"
  region = "Nordrhein-Westfalen"
  repo = "nordrhein-westfalen"
