baseURL = "https://lokal.ninja/nordrhein-westfalen"
languageCode = "de-DE"
title = "Nordrhein-Westfalen"
theme = "ln-base"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Lokal Ninja"
  org = "lokal-ninja"
  repo = "nordrhein-westfalen"
